# Generated by Django 2.2.9 on 2020-01-07 15:21

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='write down in markdown format', verbose_name='本文'),
        ),
    ]
