# Generated by Django 2.2.9 on 2020-01-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200108_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='プロジェクト名')),
                ('slug', models.SlugField(unique=True, verbose_name='プロジェクトスラグ')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('article', 'Article'), ('short_code', 'ShortCode')], default='article', max_length=50, verbose_name='タイプ'),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', '下書き'), ('released', '公開')], default='draft', max_length=50, verbose_name='状態'),
        ),
    ]
