# Generated by Django 2.2.9 on 2020-01-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200108_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='release_condition',
            field=models.CharField(choices=[('public', '全員に公開'), ('limited', 'LIMITED')], default='limited', max_length=50, verbose_name='閲覧制限'),
        ),
    ]
