# Generated by Django 2.2.9 on 2020-01-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_filelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='release_condition',
            field=models.CharField(choices=[('public', '全員に公開'), ('limited', 'LIMITED')], default='limited', max_length=50, verbose_name='閲覧制限'),
        ),
    ]
